name: Installer Release

on:
  release:
    types: [ 'released' ]

jobs:
  build:
    name: Build
    runs-on: signing
    steps:
    - name: Check out code into the right branch
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build and sign installer
      run: |
          cd ${{ github.workspace }}
          
          $env:GOOS = "linux"
          $env:GOARCH = "amd64"
          go build -o utmstack_collectors_installer -v .
          
          $env:GOOS = "windows"
          go build -o utmstack_collectors_installer.exe -v .
          signtool sign /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 /f "${{ vars.SIGN_CERT }}" /csp "eToken Base Cryptographic Provider" /k "[{{${{ secrets.SIGN_KEY }}}}]=${{ secrets.SIGN_CONTAINER }}" "utmstack_collectors_installer.exe"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: ./CHANGELOG.md
        draft: false
        prerelease: false
        files: |
          ./utmstack_collectors_installer
          ./utmstack_collectors_installer.exe
